### ISSUE TITLE
nodewatcher needs a recovery mechanism when Connection Dropped.

### ISSUE THREAD

**Issue by yjkimjunior** [paritytech/Nomidot#106]
Currently we need to update the container to start syncing from the block where connection was dropped, then restart the pods manually.

Ideally we'd have a way for this to happen automatically.

The error: 
` API-WS: disconnected from wss://kusama-rpc.polkadot.io/ code: '1006' reason: 'Connection dropped by remote peer.'`

**Comment by yjkimjunior** [comment]
FWICT, `autoconnect` is default true on the api provider end so it does continue to try to reconnect...

whenever this happens in a browser, we just reload. 

when this happens in a pod we need to restart.

from what i've read, you just have to do it manually. https://stackoverflow.com/questions/46123457/restart-container-within-pod?rq=1

**Comment by yjkimjunior** [comment]
Update:
ok so debugging this with Felix, what we're seeing is that Memory spikes around the same time when Stackdriver is logging that websocket connection refused, which is why the Pod gets Evicted rather than continuously trying to reconnect.

<img width="1173" alt="Screenshot 2020-02-10 at 12 44 01" src="https://user-images.githubusercontent.com/10432070/74147323-41c0f900-4c03-11ea-9be0-8094aab6002f.png">

So now we'll try to run a new job where we purposely set an incorrect endpoint and see if this memory spike happens then as well.

**Comment by yjkimjunior** [comment]
currently trying: remove the backofflimit

**Comment by Tbaut** [comment]
FWIW I just witnessed a pod printing API-WS: disconnected from wss://kusama-rpc.polkadot.io/ code: '1006' reason: 'connection failed' during 3.5min and then keep going when things went back to normal, so that's pretty cool.

Also it printed a couple:
```bash
2020-02-18 16:07:18    NODE-WATCHER: Writing: {"amount":"0x00000000000000007581be1bb86640cd"}
2020-02-18 16:07:18    NODE-WATCHER: FetchError: request to http://10.0.9.43:4466 failed, reason: connect ECONNREFUSED 10.0.9.43:4466
    at ClientRequest.<anonymous> (/node_watcher/node_modules/isomorphic-fetch/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:196:13)
    at ClientRequest.EventEmitter.emit (domain.js:471:20)
    at Socket.socketErrorListener (_http_client.js:402:9)
    at Socket.emit (events.js:196:13)
    at Socket.EventEmitter.emit (domain.js:471:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:83:17) {
  name: 'FetchError',
  message: 'request to http://10.0.9.43:4466 failed, ' +
    'reason: connect ECONNREFUSED ' +
    '10.0.9.43:4466',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
2020-02-18 16:07:18    NODE-WATCHER: Task --- createNominationAndValidators
```

But it kept going..

**Comment by yjkimjunior** [comment]
still happens from time to time, it takes about 50 seconds to fix it manually so I'd still make this low priority till we have other core features built out.

**Comment by Tbaut** [comment]
Found a job in this state this morning (it stayed like this all night). It was in "running" status, not evicted, and no error...
```bash
2020-03-11 23:55:00    NODE-WATCHER: Task --- createReferendumStatusUpdate
2020-03-11 23:55:00    NODE-WATCHER: Writing: []
2020-03-11 23:55:12    NODE-WATCHER: WAITING FINALIZED.
2020-03-11 23:55:12    NODE-WATCHER: blockIndex: 1410429
2020-03-11 23:55:12    NODE-WATCHER: lastKnownBestFinalized: 1410429
2020-03-11 23:55:12    NODE-WATCHER: block: 1410429
2020-03-11 23:55:12          API-WS: disconnected from wss://kusama-rpc.polkadot.io/ code: '1001' reason: 'Remote peer is going away'
```
