### ISSUE TITLE
nomidot-app-server: nested query resolvers returning null?

### ISSUE THREAD

**Issue by yjkimjunior** [paritytech/Nomidot#165]
the logs
```
Error: Cannot return null for non-nullable field TotalIssuance.blockNumber.
    at completeValue (/server/node_modules/graphql/execution/execute.js:560:13)
    at completeValueCatchingError (/server/node_modules/graphql/execution/execute.js:495:19)
    at resolveField (/server/node_modules/graphql/execution/execute.js:435:10)
    at executeFields (/server/node_modules/graphql/execution/execute.js:275:18)
    at collectAndExecuteSubfields (/server/node_modules/graphql/execution/execute.js:713:10)
    at completeObjectValue (/server/node_modules/graphql/execution/execute.js:703:10)
    at completeValue (/server/node_modules/graphql/execution/execute.js:591:12)
    at completeValueCatchingError (/server/node_modules/graphql/execution/execute.js:495:19)
    at /server/node_modules/graphql/execution/execute.js:618:25
    at Array.forEach (<anonymous>)
Error: Cannot return null for non-nullable field TotalIssuance.blockNumber.
    at completeValue (/server/node_modules/graphql/execution/execute.js:560:13)
    at completeValueCatchingError (/server/node_modules/graphql/execution/execute.js:495:19)
    at resolveField (/server/node_modules/graphql/execution/execute.js:435:10)
    at executeFields (/server/node_modules/graphql/execution/execute.js:275:18)
    at collectAndExecuteSubfields (/server/node_modules/graphql/execution/execute.js:713:10)
    at completeObjectValue (/server/node_modules/graphql/execution/execute.js:703:10)
    at completeValue (/server/node_modules/graphql/execution/execute.js:591:12)
    at completeValueCatchingError (/server/node_modules/graphql/execution/execute.js:495:19)
    at /server/node_modules/graphql/execution/execute.js:618:25
    at Array.forEach (<anonymous>)
Error: GraphQL Error: {
  "0": "T",
  "1": "h",
  "2": "e",
  "3": " ",
  "4": "s",
  "5": "e",
  "6": "r",
  "7": "v",
  "8": "e",
  "9": "r",
  "10": " ",
  "11": "w",
  "12": "a",
  "13": "s",
  "14": " ",
  "15": "n",
  "16": "o",
  "17": "t",
  "18": " ",
  "19": "a",
  "20": "b",
  "21": "l",
  "22": "e",
  "23": " ",
  "24": "t",
  "25": "o",
  "26": " ",
  "27": "p",
  "28": "r",
  "29": "o",
  "30": "d",
  "31": "u",
  "32": "c",
  "33": "e",
  "34": " ",
  "35": "a",
  "36": " ",
  "37": "t",
  "38": "i",
  "39": "m",
  "40": "e",
  "41": "l",
  "42": "y",
  "43": " ",
  "44": "r",
  "45": "e",
  "46": "s",
  "47": "p",
  "48": "o",
  "49": "n",
  "50": "s",
  "51": "e",
  "52": " ",
  "53": "t",
  "54": "o",
  "55": " ",
  "56": "y",
  "57": "o",
  "58": "u",
  "59": "r",
  "60": " ",
  "61": "r",
  "62": "e",
  "63": "q",
  "64": "u",
  "65": "e",
  "66": "s",
  "67": "t",
  "68": ".",
  "69": "\r",
  "70": "\n",
  "71": "P",
  "72": "l",
  "73": "e",
  "74": "a",
  "75": "s",
  "76": "e",
  "77": " ",
  "78": "t",
  "79": "r",
  "80": "y",
  "81": " ",
  "82": "a",
  "83": "g",
  "84": "a",
  "85": "i",
  "86": "n",
  "87": " ",
  "88": "i",
  "89": "n",
  "90": " ",
  "91": "a",
  "92": " ",
  "93": "s",
  "94": "h",
  "95": "o",
  "96": "r",
  "97": "t",
  "98": " ",
  "99": "w",
  "100": "h",
  "101": "i",
  "102": "l",
  "103": "e",
  "104": "!",
  "status": 503
}
    at BatchedGraphQLClient.<anonymous> (/server/node_modules/http-link-dataloader/src/BatchedGraphQLClient.ts:59:13)
    at step (/server/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
    at Object.next (/server/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
    at fulfilled (/server/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
FetchError: request to http://10.0.9.43:4466/ failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/server/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1393:11)
    at ClientRequest.emit (events.js:210:5)
    at ClientRequest.EventEmitter.emit (domain.js:478:20)
    at Socket.socketErrorListener (_http_client.js:407:9)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:478:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by yjkimjunior** [comment]
https://www.prisma.io/tutorials/a-guide-to-common-resolver-patterns-ct08/#scenario:-implementing-relations-with-prisma-client
