### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Option: unwrapping a None value

### ISSUE THREAD

**Issue by Tbaut** [paritytech/Nomidot#173]
The last 50k job halted at:
```bash
2020-02-13 22:10:59    NODE-WATCHER: Task --- createEra
2020-02-13 22:10:59       TASK: ERA: NomidotEra: {"idx":411,"points":{"total":53440,"individual":[340,260,500,240,380,300,520,460,300,300,220,380,260,460,420,400,520,240,400,320,360,520,380,500,340,80,400,500,220,140,340,460,320,460,380,300,380,400,300,460,400,460,240,500,420,440,200,380,320,340,340,360,400,80,320,260,160,520,380,120,280,420,280,380,340,360,360,460,320,500,360,360,300,360,340,400,460,0,400,420,260,440,120,380,420,240,540,400,360,420,560,340,0,360,280,400,300,340,440,140,420,240,320,320,140,300,140,540,420,320,160,260,260,280,340,460,360,260,400,380,200,300,440,240,400,300,260,260,20,300,540,440,60,340,360,440,320,260,440,480,300,520,240,80,300,340,300,240,0,300,320,340,400,320,360,380,200,380,180,280]},"startSessionIndex":1803}
2020-02-13 22:10:59    NODE-WATCHER: Writing: {"idx":411,"points":{"total":53440,"individual":[340,260,500,240,380,300,520,460,300,300,220,380,260,460,420,400,520,240,400,320,360,520,380,500,340,80,400,500,220,140,340,460,320,460,380,300,380,400,300,460,400,460,240,500,420,440,200,380,320,340,340,360,400,80,320,260,160,520,380,120,280,420,280,380,340,360,360,460,320,500,360,360,300,360,340,400,460,0,400,420,260,440,120,380,420,240,540,400,360,420,560,340,0,360,280,400,300,340,440,140,420,240,320,320,140,300,140,540,420,320,160,260,260,280,340,460,360,260,400,380,200,300,440,240,400,300,260,260,20,300,540,440,60,340,360,440,320,260,440,480,300,520,240,80,300,340,300,240,0,300,320,340,400,320,360,380,200,380,180,280]},"startSessionIndex":1803}
2020-02-13 22:10:59    NODE-WATCHER: Task --- createSlashing
2020-02-13 22:10:59  TASK: SLASHING: Nomidot Slashing: []
2020-02-13 22:10:59    NODE-WATCHER: Writing: []
2020-02-13 22:10:59    NODE-WATCHER: Task --- createTotalIssuance
2020-02-13 22:10:59 TASK: TOTALISSUANCE: Total Issuance: {"amount":"0x000000000000000074e4cd14df30fe3d"}
2020-02-13 22:10:59    NODE-WATCHER: Writing: {"amount":"0x000000000000000074e4cd14df30fe3d"}
2020-02-13 22:10:59    NODE-WATCHER: Task --- createNominationAndValidators
(node:26) UnhandledPromiseRejectionWarning: Error: Option: unwrapping a None value
    at Option.unwrap (/node_watcher/node_modules/@polkadot/types/codec/Option.js:170:13)
    at /node_watcher/src/tasks/createNominationAndValidators.ts:111:26
    at step (/node_watcher/src/tasks/createNominationAndValidators.ts:36:23)
    at Object.next (/node_watcher/src/tasks/createNominationAndValidators.ts:17:53)
    at fulfilled (/node_watcher/src/tasks/createNominationAndValidators.ts:8:58)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
(node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Tbaut** [comment]
I had this because I skipped the blocks where the motion gets Approved and executed. 
Running the following in a row worked well..

```bash
pre image 964699 			PRISMA_ENDPOINT=http://0.0.0.0:4466 yarn prisma reset && PRISMA_ENDPOINT=http://0.0.0.0:4466 START_FROM="964699" yarn start
motion creation 964710 		PRISMA_ENDPOINT=http://0.0.0.0:4466 START_FROM="964710" yarn start
motion approved 971490 		PRISMA_ENDPOINT=http://0.0.0.0:4466 START_FROM="971490" yarn start
referendum starts 1008000 		PRISMA_ENDPOINT=http://0.0.0.0:4466 START_FROM="1008000" yarn start
```
