### ISSUE TITLE
nodewatcher: Motion $where input type

### ISSUE THREAD

**Issue by yjkimjunior** [paritytech/Nomidot#177]
blockIndex: 190,800
job-name:  `nomidotwatcher-160366`
pod-name: `nomidotwatcher-160366-8h4n2`

```
2020-02-13 22:06:45    NODE-WATCHER: Task --- createMotionStatusUpdate
(node:26) UnhandledPromiseRejectionWarning: Error: Variable '$where' cannot be non input type 'MotionWhereInput'. (line 1, column 16):
query ($where: MotionWhereInput) {
               ^
    at BatchedGraphQLClient.<anonymous> (/node_watcher/node_modules/http-link-dataloader/src/BatchedGraphQLClient.ts:74:13)
    at step (/node_watcher/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
    at Object.next (/node_watcher/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
    at fulfilled (/node_watcher/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
(node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
YJs-MacBook-Pro:~ yj$ kubectl logs nomidotwatcher-160366-8h4n2 --tail=10
(node:26) UnhandledPromiseRejectionWarning: Error: Variable '$where' cannot be non input type 'MotionWhereInput'. (line 1, column 16):
query ($where: MotionWhereInput) {
               ^
    at BatchedGraphQLClient.<anonymous> (/node_watcher/node_modules/http-link-dataloader/src/BatchedGraphQLClient.ts:74:13)
    at step (/node_watcher/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
    at Object.next (/node_watcher/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
    at fulfilled (/node_watcher/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
```

**Comment by Tbaut** [comment]
This happens when we start a job at a block number and there's a status update for a motion that has actually never been created (not in the DB).

The motion should have been created at 163670 which is between 190800 and 160366 though.. I'll try to reproduce.

Should I really prevent the job from failing though? If node watcher is indexing blocks and skips things because the sync hasn't been done in order is problematic. I generally pick my starting block according to that, but I understand it's a pain for you.

**Comment by yjkimjunior** [comment]
yeah in the case the motion doesn't exist in the DB, we expect it to fail, just that it looks like it fails for some other reason as you mentioned.

**Comment by Tbaut** [comment]
I've a hard time reproducing this :(
Is that job old?

Launching on an empty DB on `190800` doesn't throw and there's just an error printed.
Things look good if I have the motion in the DB of course.

I'll launch the job locally and hope to get the same.

**Comment by Tbaut** [comment]
Looking at the logs where the motion should have been created, there was an error there as well:
```bash
2020-02-13 18:27:45.730 CET
2020-02-13 17:27:45 NODE-WATCHER: Error: Variable '$data' cannot be non input type 'MotionCreateInput!'. (line 1, column 18):
2020-02-13 18:27:45.730 CET
mutation ($data: MotionCreateInput!) {
2020-02-13 18:27:45.730 CET
^
2020-02-13 18:27:45.730 CET
at BatchedGraphQLClient.<anonymous> (/node_watcher/node_modules/http-link-dataloader/src/BatchedGraphQLClient.ts:74:13)
2020-02-13 18:27:45.730 CET
at step (/node_watcher/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
2020-02-13 18:27:45.730 CET
at Object.next (/node_watcher/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
2020-02-13 18:27:45.730 CET
at fulfilled (/node_watcher/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
2020-02-13 18:27:45.730 CET
at processTicksAndRejections (internal/process/task_queues.js:88:5) {
2020-02-13 18:27:45.730 CET
result: { data: null, errors: [ [Object], [Object], [Object] ], status: 200 }
2020-02-13 18:27:45.730 CET
}
```

This to me points in the same direction: the DB wasn't updated.

**Comment by yjkimjunior** [comment]
yess, there is no way to "update" something yet. Sorry haven't been keeping close track of your schema updates.

I'm thinking right now we could a field to the NomidotTask so it looks like this:

```
NomidotTask = {
  read: () => {},
  write: () => {},
  update: () => {}
}
```

otherwise, if there is some set of entries whose formats need to be updated somehow, they'd need to be written into another db.

**Comment by Tbaut** [comment]
Not sure if there is a misunderstanding here. I actually never really update a row, What we do eventually is to link a row from a table to another row on another table (using prisma.connect) but we never update any row.

What I meant with  the "DB wasn't updated." is that the db **schema** wasn't updated. There were changes in the schema before this week-end that were not reflected in the cloudsql DB. E.g a [dumb name change](https://github.com/paritytech/Nomidot/pull/167), we end up running a newer code against an old DB schema, and I actually think this name change was the problem. I did a `prisma deploy` in the mean time, so my hope is that this error will not happen again.

**Comment by Tbaut** [comment]
Above, the logs shows that it tries to write `"status":"Proposed"`, although the new field name was `motionStatus`. This is the problem indeed. The job is running with an incompatible code. My bad sorry about that.
