### ISSUE TITLE
BlockIndex doesn't seem to work

### ISSUE THREAD

**Issue by Tbaut** [paritytech/Nomidot#221]
```gql
query blockIndexs{
  blockIndexes (last: 10){
    identifier
    id
    startFrom
    index
  }
}
```
returns the following
```json
{
  "data": {
    "blockIndexes": [
      {
        "identifier": "last-50k",
        "id": "ck79jujdgoqju0719tuo6b984",
        "startFrom": 1177733,
        "index": 1281969
      }
    ]
  }
}
```
Relaunching [the job](https://github.com/paritytech/Nomidot/blob/master/back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml#L33-L38) that was launched before (and got evicted) yields:

```bash
kubectl logs nomidotwatcher-last-50k-mzlbt -n nodewatcher-staging --tail=100 --follow
yarn run v1.15.2
$ node -r ts-node/register --max-old-space-size=8192 ./src/index.ts
2020-03-03 10:51:19    NODE-WATCHER: blockIndex: 1135256
2020-03-03 10:51:19    NODE-WATCHER: lastKnownBestFinalized: 1289557
2020-03-03 10:51:19    NODE-WATCHER: block: 1135256
2020-03-03 10:51:19    NODE-WATCHER: hash: 0x0b4118b6c958ca8c703595bdf8690a8c0a6e482d621b0e683f92910d815e6136
2020-03-03 10:51:19    NODE-WATCHER: bumped spec version to 1045, fetching new metadata
2020-03-03 10:51:20    NODE-WATCHER: Task --- createBlockNumber
2020-03-03 10:51:20 TASK: BLOCKNUMBER: NomidotBlock: {"authoredBy":"Cg9auGgeVENvV52kprFr5RqUYfNC45MD78iJ72qpG62Tx8X","hash":"0x0b4118b6c958ca8c703595bdf8690a8c0a6e482d621b0e683f92910d815e6136","startDateTime":1582288362000}
2020-03-03 10:51:20    NODE-WATCHER: Writing: {"authoredBy":"Cg9auGgeVENvV52kprFr5RqUYfNC45MD78iJ72qpG62Tx8X","hash":"0x0b4118b6c958ca8c703595bdf8690a8c0a6e482d621b0e683f92910d815e6136","startDateTime":1582288362000}
2020-03-03 10:51:20    NODE-WATCHER: Error: A unique constraint would be violated on BlockNumber. Details: Field name = number
    at BatchedGraphQLClient.<anonymous> (/node_watcher/node_modules/http-link-dataloader/src/BatchedGraphQLClient.ts:74:13)
    at step (/node_watcher/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
    at Object.next (/node_watcher/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
    at fulfilled (/node_watcher/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
    at processTicksAndRejections (internal/process/task_queues.js:88:5) {
  result: { data: null, errors: [ [Object] ], status: 200 }
```

It stated from `1135256`.. no idea why. The index shows `1281969` and the original `START_FROM` is `1177733`

**Comment by yjkimjunior** [comment]
hmm maybe it was using an older container image? shot in the dark, but this has happened to me before...

**Comment by Tbaut** [comment]
So, some more info as something along the same line happened just now.
A pod is running, and prints:
```bash
kubectl logs nomidotwatcher-last-50k-n9smk -n nodewatcher-staging --tail=100 --follow
yarn run v1.15.2
$ node -r ts-node/register --max-old-space-size=8192 ./src/index.ts
2020-03-04 14:47:20    NODE-WATCHER: blockIndex: 1281969
2020-03-04 14:47:20    NODE-WATCHER: lastKnownBestFinalized: 1305931
2020-03-04 14:43:52    NODE-WATCHER: block: 1305897
```

So it's at block 1305897, but the index is behind, at 1281969.
I stop the job and relaunch it with `START_FROM=1305897` and it prints:
```bash
kubectl logs nomidotwatcher-last-50k-n9smk -n nodewatcher-staging --tail=100 --follow
yarn run v1.15.2
$ node -r ts-node/register --max-old-space-size=8192 ./src/index.ts
2020-03-04 14:47:20    NODE-WATCHER: blockIndex: 1281969
2020-03-04 14:47:20    NODE-WATCHER: lastKnownBestFinalized: 1305931
2020-03-04 14:47:20    NODE-WATCHER: block: 1281969
```
So the START_FROM=1305897 is ignored, which is fine, and it starts back at the old index.
Creating a new identifier works as expected, here is goes with a new identifier:
```bash
kubectl logs nomidotwatcher-last-50k-hf278 -n nodewatcher-staging --tail=100 --follow
yarn run v1.15.2
$ node -r ts-node/register --max-old-space-size=8192 ./src/index.ts
2020-03-04 14:48:15    NODE-WATCHER: blockIndex: 1305897
2020-03-04 14:48:15    NODE-WATCHER: lastKnownBestFinalized: 1305940
2020-03-04 14:48:15    NODE-WATCHER: block: 1305897
```

**Comment by Tbaut** [comment]
closing this, it worked everytime I tried in the past weeks.
