### ISSUE TITLE
Cannot read property 'at' of undefined

### ISSUE THREAD

**Issue by Tbaut** [paritytech/Nomidot#233]
```bash
$ node -r ts-node/register --max-old-space-size=8192 ./src/index.ts
Unknown types found, no types for ActiveEraInfo,Releases
2020-03-09 21:01:03    NODE-WATCHER: blockIndex: 1378323
2020-03-09 21:01:03    NODE-WATCHER: lastKnownBestFinalized: 1380087
2020-03-09 21:01:03    NODE-WATCHER: block: 1378323
2020-03-09 21:01:22    NODE-WATCHER: hash: 0x6c70cbdecaeb1a6b3507c8dcc9e437eb9d0f40a6d3f8a95fb1df66e993da5dfa
2020-03-09 21:01:40    NODE-WATCHER: bumped spec version to 1050, fetching new metadata
2020-03-09 21:02:53    NODE-WATCHER: Task --- createBlockNumber
2020-03-09 21:03:29 TASK: BLOCKNUMBER: NomidotBlock: {"authoredBy":"DxnzP6bkiF2SeQofK4o8shvgK5JyGsqrNjpd7qPtLZffiAG","hash":"0x6c70cbdecaeb1a6b3507c8dcc9e437eb9d0f40a6d3f8a95fb1df66e993da5dfa","startDateTime":1583776788000}
2020-03-09 21:03:29    NODE-WATCHER: Writing: {"authoredBy":"DxnzP6bkiF2SeQofK4o8shvgK5JyGsqrNjpd7qPtLZffiAG","hash":"0x6c70cbdecaeb1a6b3507c8dcc9e437eb9d0f40a6d3f8a95fb1df66e993da5dfa","startDateTime":1583776788000}
2020-03-09 21:03:29 TASK: BLOCKNUMBER: Prisma Block Number: {"number":1378323,"startDateTime":"2020-03-09T17:59:48.000Z","hash":"0x6c70cbdecaeb1a6b3507c8dcc9e437eb9d0f40a6d3f8a95fb1df66e993da5dfa","id":"ck7kydbbmw44x07191z8nat24","authoredBy":"DxnzP6bkiF2SeQofK4o8shvgK5JyGsqrNjpd7qPtLZffiAG"}
2020-03-09 21:03:29    NODE-WATCHER: Task --- createCouncil
2020-03-09 21:03:29    NODE-WATCHER: Writing: []
2020-03-09 21:03:29    NODE-WATCHER: Task --- createSession
2020-03-09 21:03:29   TASK: SESSION: Nomidot Session: {"didNewSessionStart":false,"idx":2448}
2020-03-09 21:03:29    NODE-WATCHER: Writing: {"didNewSessionStart":false,"idx":2448}
2020-03-09 21:03:29    NODE-WATCHER: Task --- createStake

Task --- createStake
(node:26) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'at' of undefined
    at /node_watcher/src/tasks/createStake.ts:26:67
    at step (/node_watcher/src/tasks/createStake.ts:36:23)
    at Object.next (/node_watcher/src/tasks/createStake.ts:17:53)
    at /node_watcher/src/tasks/createStake.ts:11:71
    at new Promise (<anonymous>)
    at __awaiter (/node_watcher/src/tasks/createStake.ts:7:12)
    at Object.read (/node_watcher/src/tasks/createStake.ts:24:20)
    at /node_watcher/src/nodeWatcher.ts:121:33
    at step (/node_watcher/src/nodeWatcher.ts:36:23)
    at Object.next (/node_watcher/src/nodeWatcher.ts:17:53)
(node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:26) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Tbaut** [comment]
Same for era:
```bash
2020-03-09 22:22:23    NODE-WATCHER: Task --- createEra
(node:26) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'at' of undefined
    at /node_watcher/src/tasks/createEra.ts:25:67
    at step (/node_watcher/src/tasks/createEra.ts:36:23)
    at Object.next (/node_watcher/src/tasks/createEra.ts:17:53)
    at fulfilled (/node_watcher/src/tasks/createEra.ts:8:58)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
    at runNextTicks (internal/process/task_queues.js:58:3)
    at processImmediate (internal/timers.js:412:9)
(node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by Tbaut** [comment]
hmm that's super werid, same for createNominationAndValidators:
```js
2020-03-10 04:42:30    NODE-WATCHER: Task --- createNominationAndValidators
(node:26) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'at' of undefined
    at /node_watcher/src/tasks/createNominationAndValidators.ts:88:70
    at step (/node_watcher/src/tasks/createNominationAndValidators.ts:36:23)
    at Object.next (/node_watcher/src/tasks/createNominationAndValidators.ts:17:53)
    at fulfilled (/node_watcher/src/tasks/createNominationAndValidators.ts:8:58)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
(node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by amaurymartiny** [comment]
Possibly related to https://github.com/polkadot-js/api/blob/master/CHANGELOG.md#162-mar-12-2020

**Comment by yjkimjunior** [comment]
is this still happening? i see there is a job running at the tip at the moment

**Comment by yjkimjunior** [comment]
fixed: https://github.com/paritytech/Nomidot/pull/252
