### ISSUE TITLE
Prisma DB not reachable despite no error

### ISSUE THREAD

**Issue by Tbaut** [paritytech/Nomidot#249]
The pod show no error:
```bash
kubectl -n nodewatcher-staging logs nodewatcher-6967444867-vnhj4 -c prisma --tail 100 --follow
No log level set, defaulting to INFO.
[INFO] {} - Starting...
[INFO] {} - Start completed.
[INFO] Initializing workers...
[INFO] Obtaining exclusive agent lock...
[INFO] Successfully started 1 workers.
[INFO] Obtaining exclusive agent lock... Successful.
[INFO] Deployment worker initialization complete.
Server running on :4466
```

But connecting to it fails, on chain-db watcher:
```bash
 FetchError: request to http://35.189.196.74:4000/ failed, reason: socket hang up
```

And on the server:
```bash
nomidot-server is failing with FetchError: request to http://10.0.9.43:4466/ failed, reason: read ECONNRESET at ClientRequest. (/server/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1393:11) at ClientRequest.emit (events.js:196:13) at ClientRequest.EventEmitter.emit (domain.js:471:20) at Socket.socketErrorListener (_http_client.js:402:9) at Socket.emit (events.js:196:13) at Socket.EventEmitter.emit (domain.js:471:20) at emitErrorNT (internal/streams/destroy.js:91:8) at emitErrorAndCloseNT (internal/streams/destroy.js:59:3) at processTicksAndRejections (internal/process/task_queues.js:83:17)
```

deleting the nodewatcher pod usually solved the problem.
Next time this happens we need to `kubectl -n nodewatcher-staging describe pod/<pod-name>` next time this happens.

**Comment by Tbaut** [comment]
closing, same as #271
