### ISSUE TITLE
No Node for the model Session with value 2832 for index found.

### ISSUE THREAD

**Issue by Tbaut** [paritytech/Nomidot#259]
What I reported https://github.com/paritytech/Nomidot/pull/252#issuecomment-603132632 happens in last-50k job for instance at block 1603579

```bash
2020-03-25 16:35:09    NODE-WATCHER: Task --- createEra
2020-03-25 16:35:09       TASK: ERA: NomidotEra: {"idx":587,"points":{"total":0,"individual":{}},"startSessionIndex":2832}
2020-03-25 16:35:09    NODE-WATCHER: Writing: {"idx":587,"points":{"total":0,"individual":{}},"startSessionIndex":2832}
2020-03-25 16:35:09    NODE-WATCHER: Error: No Node for the model Session with value 2832 for index found.
    at BatchedGraphQLClient.<anonymous> (/node_watcher/node_modules/http-link-dataloader/src/BatchedGraphQLClient.ts:74:13)
    at step (/node_watcher/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
    at Object.next (/node_watcher/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
    at fulfilled (/node_watcher/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
    at processTicksAndRejections (internal/process/task_queues.js:88:5) {
  result: { data: null, errors: [ [Object] ], status: 200 }
}
```

**Comment by yjkimjunior** [comment]
it seems these do exist though, and session is up to date in the logs 

<img width="1183" alt="Screenshot 2020-03-30 at 11 50 54" src="https://user-images.githubusercontent.com/10432070/77873533-d7304f00-727c-11ea-8023-99574dbc3b04.png">


<img width="1094" alt="Screenshot 2020-03-30 at 11 50 50" src="https://user-images.githubusercontent.com/10432070/77873529-d39cc800-727c-11ea-879c-a56eff08dbdd.png">
