### ISSUE TITLE
New proposals not written to DB

### ISSUE THREAD

**Issue by Tbaut** [paritytech/Nomidot#304]
I broke something with #292 
```bash
NODE-WATCHER: Error: Variable '$data' expected value of type 'ProposalStatusCreateInput!' but got: {"blockNumber":{"connect":{"number":1915200}},"proposal":{"connect":{"proposalId":17}},"status":"Tabled"}. Reason: 'uniqueStatus' Expected non-null value, found null. (line 1, column 11):
mutation ($data: ProposalStatusCreateInput!) {
          ^
    at BatchedGraphQLClient.<anonymous> (/node_watcher/node_modules/http-link-dataloader/src/BatchedGraphQLClient.ts:74:13)
    at step (/node_watcher/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
    at Object.next (/node_watcher/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
    at fulfilled (/node_watcher/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
    at processTicksAndRejections (internal/process/task_queues.js:88:5) {
  result: { data: null, errors: [ [Object] ], status: 200 }
}
```

**Comment by Tbaut** [comment]
it looks like the image we use isn't from master.

**Comment by Tbaut** [comment]
Weird, what's in master is not the same sha as the last image https://github.com/paritytech/Nomidot/pull/293/files reverting to that.

**Comment by Tbaut** [comment]
I can't understand that. `master` has the image sha `38a..` here: https://github.com/paritytech/Nomidot/blame/master/back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml#L30
from [#284](https://github.com/paritytech/Nomidot/pull/284)

Which should have been changed then by #293 for `f88.`.. but this simply does appear anywhere.

**Comment by Tbaut** [comment]
@yjkimjunior can you make sense of this ^ it looks like #293 just never happened!
